### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by felixmusil** [osscar-org/widget-code-input#1]
Hi Giovanni,

I can't seem to install through pip this widget using python 3.6. I did not try with other versions.
Here is the error message I get:
```
Could not find a version that satisfies the requirement widget_code_input (from versions: )
No matching distribution found for widget_code_input
```

Otherwise I can install the repo but it seems that the requirements are not properly read.

**Comment by yw-fang** [comment]
@felixmusil  Hi, it hasn't been released in Pypi. That's why you cannot install it by pip.

**Comment by felixmusil** [comment]
I see. It feels weird since the repository is set up to allow pip installation and the readme talks about it which is why I though of it as a bug.

**Comment by dou-du** [comment]
The newest version of this widget has been released on PyPi. 

https://pypi.org/project/widget-code-input/
