### ISSUE TITLE
Binder example too slow to open

### ISSUE THREAD

**Issue by giovannipizzi** [osscar-org/widget-code-input#10]
I've been waiting >15 minutes (15!!) to open the projectile example in binder, and binder is still building the container!

I think that
- we should keep the requirements.txt to a very minimal set (e.g. do we really ned to depend on jupyterlab to use this widget? If not, jupyterlab should *not* be in the requirements.txt; you can create a optional-requirements.txt or something like this in case)
- we should make sure the example/demos have *very minimal* dependencies. I think this is achieved by only keeping the very minimal required dependencies in `requirements.txt`. Otherwise let's discuss.

But I think it critical that demos open super quick, otherwise nobody will ever see them if they take more than 1 min to open.
@dou-du could you check the requirements and limit to really required ones? Thanks!

(Also check [this comment](https://github.com/osscar-org/widget-code-input/pull/7#issuecomment-692932912))

**Comment by dou-du** [comment]
> I've been waiting >15 minutes (15!!) to open the projectile example in binder, and binder is still building the container!
> 
> I think that
> 
> * we should keep the requirements.txt to a very minimal set (e.g. do we really ned to depend on jupyterlab to use this widget? If not, jupyterlab should _not_ be in the requirements.txt; you can create a optional-requirements.txt or something like this in case)
> * we should make sure the example/demos have _very minimal_ dependencies. I think this is achieved by only keeping the very minimal required dependencies in `requirements.txt`. Otherwise let's discuss.
> 
> But I think it critical that demos open super quick, otherwise nobody will ever see them if they take more than 1 min to open.
> @dou-du could you check the requirements and limit to really required ones? Thanks!
> 
> (Also check [this comment](https://github.com/osscar-org/widget-code-input/pull/7#issuecomment-692932912))

Thanks for checking. I just test it and it takes less than 1 min for me to get the pages. I found Binder is not very stable. Sometimes it takes very long time to open it and even timeout. Anyway, I will check all links and make the minimum required packages.

**Comment by giovannipizzi** [comment]
Thanks Dou - I think it's because I had opened it first, so it build the image for me, and since you didn't commit anything afterwards in the branch, you just reused the same image, so it was fast.
Great if you could indeed simplify the dependencies!
