### ISSUE TITLE
No error traceback of code input

### ISSUE THREAD

**Issue by agoscinski** [osscar-org/widget-code-input#12]
The error traceback does not go into the code input. Compare the error message of these two functions in the image, one time defined in a code input and one time in a usual way.
```python
from widget_code_input import WidgetCodeInput

code_input = WidgetCodeInput(
        function_name="foo", 
        function_parameters="",
        docstring="""
""",
        function_body="""
return a
"""
)
code_input.get_function_object()()
```
```python
def foo():
    return a
foo()
```
Basically you don't know in which line the error happens in the code widget.
![code_input-no_traceback_error](https://user-images.githubusercontent.com/2772557/175469609-ecb2c43f-cf00-4928-ba9e-fde4b2f8cf03.png)

**Comment by giovannipizzi** [comment]
Here is an example notebook where I add some wrapper code to display better information, both for SyntaxErrors when parsing the code, and then for any other exception (including NameError) when executing it:
[code-widget-syntax-error-example-checkpoint.ipynb.zip](https://github.com/osscar-org/widget-code-input/files/9000060/code-widget-syntax-error-example-checkpoint.ipynb.zip)

If you like the approach and the output, probably we need to think at how to put this code directly in the code widget (e.g., having the two wrapper codes directly wrapping the calls to get_function_object and wrapping the actual execution) to avoid that the user has to remember to wrap them every time? 

@dou-du @agoscinski happy to hear feedback on the suggested approach, and possibly to the integration in the code widget

**Comment by giovannipizzi** [comment]
I proposed a solution. However I worked on master, while I think I should have done it in develop? This includes the two commits I directly pushed to add black and other pre-commits... @dou-du let me know if you know how to fix it, or we should discuss

**Comment by agoscinski** [comment]
I would say there is no need to catch the error in case of an `SyntaxError` when getting the function object in `wid.widget_function_object()`, since the error is displayed correctly in this case. 

I was hoping there is an approach that forwards to the python error machinery such that we do not have this hacky way of imitating the python error message. But it seems to be a general problem of python for executed strings.
https://stackoverflow.com/questions/35564208/python-traceback-of-a-string-in-exec

So I am fine with this solution. I would just keep the same error type name add the proper coloring to the error message.
https://stackoverflow.com/a/287944
