### ISSUE TITLE
string causes problem with the widget 

### ISSUE THREAD

**Issue by dou-du** [osscar-org/widget-code-input#6]
```python
def my_function():
    return 'test'
```
When input string into the widget, it keeps throwing out errors.  It seems related to quotation mark. 
More detailed investigate needs to be done.

**Comment by giovannipizzi** [comment]
I cannot reproduce this. @dou-du an you check if this happens, or close this issue?

**Comment by dou-du** [comment]
> I cannot reproduce this. @dou-du an you check if this happens, or close this issue?

Sorry not describe the issue clearly. Actually, this is not a issue. I mean that when using the "observe" method, the function will keep throw up errors info when the return function is not completed.
